### ISSUE TITLE
command-palette launch is very slow in v1.25.0-beta

### ISSUE THREAD

**Issue by t9md** [atom/command-palette#108]
### Description

Launching by `command-palette:toggle` is very slow in Atom-v1.25.0-beta.
Why? render-on-visible #101 feature not working correctly because incorrect `{visible}` options is passed to `elementForItem`.

What is happening now on `command-palette:toggle` is "render initial 10 items" then "immediately render all items" because of incorrect visible state determination in atom-select-list

I created PR atom/atom-select-list#25  to fix this.
No change required on command-palette side.

### Steps to Reproduce

launch `command-palette:toggle`

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom v1.24.0 have no issue
Atom v1.25.0 and later have issue

**Comment by t9md** [comment]
If atom/atom-select-list#25 get merged and using that version of select-list will fix this issue.
No change required on command-palette's code.

**Comment by t9md** [comment]
You can notice big DEALY between timing from **mini-editor-open** to **mini-editor-focus**(by blue-border).

- Before fix: big GAP between mini-editor-open to blue-border-focus-indicator. Typing text is not immediately inputed to mini-editor
- After fix: no GAP, immediate focused-blue-border on open mini-editor. Can start typing immediately

## Before fix (current atom-beta v1.25.0-beta2)

![slow-palette](https://user-images.githubusercontent.com/155205/36681072-e716d950-1b5a-11e8-83ee-13f247c26d33.gif)


# After fix (using atom/atom-select-list#25): 

![not-slow-palette](https://user-images.githubusercontent.com/155205/36681075-e9122610-1b5a-11e8-8e43-2afe289a298b.gif)


## Before fix.

Command rendered in 2 steps.
step 1 render 10 command, then show mini-editor(its' OK).
step 2 render rest of all items(over 700 if installed vim-mode-plus), which make command-palette's UX really slow.

Step 2 rendering is just unnecessary rendering since its invisible item. But because of BUG it's happening.

It spend long time for `visibilityObserver.change` related function call.
Which actually rendering all command(over 700 command in my case since I'm vim-mode-plus user).
This is just bug, fixed it in atom/atom-select-list#25.
<img width="1594" alt="command-palette-view_js_ ___github_command-palette" src="https://user-images.githubusercontent.com/155205/36681457-0cb66fee-1b5c-11e8-85e3-f9b3b28d4ce0.png">

**Comment by daviwil** [comment]
Fixed by https://github.com/atom/atom-select-list/pull/25
