### ISSUE TITLE
The 'Run in Atom' context menu is not showing up

### ISSUE THREAD

**Issue by DinisCruz** [atom/command-palette#26]
This what I'm getting 

![image](https://cloud.githubusercontent.com/assets/656739/5683906/ad124ee6-9823-11e4-90a8-9b02ca65be90.png)

the palette window command seems to be working

![image](https://cloud.githubusercontent.com/assets/656739/5683911/bbe52f56-9823-11e4-9d4b-498777c30ae9.png)

**Comment by benogle** [comment]
This issue was moved to robenkleene/run-in-atom#1

**Comment by DinisCruz** [comment]
yes, sorry, I've posted it on the wrong repo.

Thx for moving it
