### ISSUE TITLE
A method to save position

### ISSUE THREAD

**Issue by TheBestPessimist** [atom/command-palette#27]
This is an odd one: i would like to be able to save the position where i was in the command palette after choosing an option, instead of the palette always opening at the top (starting with the letter a).
This should only happen if i don't search for anything, of course.
Could this be made as an option in package settings?

**Comment by thedaniel** [comment]
I also want something like this, and think it should be the default. An alternative implementation would be not to save the last fuzzy search (still "start with the letter a" in other words) but prepend the last executed command to the top of the list so that I could re-run a command by cmd-P, :arrow_down:

**Comment by TheBestPessimist** [comment]
@thedaniel, what i want is different: i want that if i simply press down- down - down until i reach say "Styleguide: show" and then i press any other key, as to close the menu, i want when i press ctrl shit p again to be at that "Styleguide: show" position.

**Comment by crantok** [comment]
Lighttable does something similar to this. I've found it very useful when wanting to execute the same command multiple times when I have not set up a keybinding.

When the Lighttable command palette is opened, the typed text that the palette contained last time it was used is still there. This means that, initially, the results of the previous fuzzy search are still displayed. In addition, the typed text is all selected, so if the user wants to search for a different command then they can just start typing as normal; no special action required.

I loved this feature and would love to see it in atom.
