### ISSUE TITLE
Order command palette results by matching score

### ISSUE THREAD

**Issue by nicktimko** [atom/command-palette#28]
When searching for commands in the palette, the order is usually baffling (see #2). Short of #18, which requires use in order to get tuned, I propose ordering the commands by how well they match the search term. Ideally if I type a word, if it exists, unbroken, and perhaps in it's entirety, I would expect to see those results above F**in**d And Replace: **S**elec**t All**

I do like the idea of #18, but one can argue about the UX, a la the [adaptive menus in Office 2000](http://blogs.msdn.com/b/jensenh/archive/2006/03/31/565877.aspx) wherein shuffling around commands should be done with care. This proposes to keep a fixed order for any given search term.

![image](https://cloud.githubusercontent.com/assets/5297556/6005698/fcabbe68-aad1-11e4-93ad-988e60b6598c.png)

**Comment by alexchandel** [comment]
This issue is infuriating, and it makes demos of Atom go hilariously bad.

```
A: Watch how easy it is to install packages!
<Cmd+P, i,n,s,t,a,l,l>
A: ...
B: I'm gonna stick to X, thanks.
```

**Comment by FunkMonkey** [comment]
:+1: 

The package that is used for fuzzy matching, [atom/fuzzaldrin](https://github.com/atom/fuzzaldrin), even provides a scorer. Implementing it should thus be relatively easy. Dunno about performance though...

**Comment by jcuenod** [comment]
Is anything happening on this because infuriating is a good word to describe this issue...

**Comment by 50Wliu** [comment]
@jcuenod Make sure you're on Atom 1.2.0, then go to the Command Palette options and enable the Alternate Scoring option.

**Comment by jcuenod** [comment]
@50Wliu ahh, I'm on 1.1.0. Thanks...

**Comment by jcuenod** [comment]
Hmm, I'm on 1.2.0 but I'm not seeing an alternate scoring option under the Command Palette settings. The only setting I see is to enable (or rather, disable) the keybinding.

**Comment by 50Wliu** [comment]
Ah, I see now.  Unfortunately, that option didn't make it into 1.2.0.  It should be in the 1.3.0 betas though if you want to try those.

**Comment by jcuenod** [comment]
Okay, thanks. I'll have a go but I kind of like having a mostly-stable editor :)

**Comment by lee-dohm** [comment]
This has been fixed for a while now and the alternate scoring is the default. Closing.
