### ISSUE TITLE
Choose needed option with 'cmd-<line-number>' hotkey

### ISSUE THREAD

**Issue by kirillsalykin** [atom/command-palette#34]
It would be very useful to mimic AlfredApp behaviour, eg select needed option with 'cmd - line-number '.
![screenshot 2015-03-16 09 52 18](https://cloud.githubusercontent.com/assets/136315/6662972/fd0b4a66-cbc1-11e4-99cf-1616df9b7d6e.png)

![screenshot 2015-03-16 09 52 58](https://cloud.githubusercontent.com/assets/136315/6662978/0f6a22ae-cbc2-11e4-8ef6-3edfb9151c76.png)
"Settings View: Install Packages And Themes" option can be choosen with 'cmd-2', so no need to touch arrows key.

**Comment by lee-dohm** [comment]
Unless the intent is for this to be specific to only the command palette (and not the fuzzy finder or other packages that use the `SelectListView`), this should probably be moved to the [atom-space-pen-views package](https://github.com/atom/atom-space-pen-views).

**Comment by kirillsalykin** [comment]
Issue moved to  atom-space-pen-views package.
https://github.com/atom/atom-space-pen-views/issues/8
