### ISSUE TITLE
Preserve last query in search input

### ISSUE THREAD

**Issue by muhasturk** [atom/command-palette#46]
Could you improve plugin that able to remember last command like Sublime does?

**Comment by izuzak** [comment]
Thanks for the suggestion, @muhasturk -- I think https://github.com/atom/command-palette/issues/18 is discussing the same request so I'm closing this in favor of that issue. Please add a comment there or just subscribe for updates.

**Comment by muhasturk** [comment]
Thank you.

**Comment by mnquintana** [comment]
@muhasturk To clarify, did you mean preserving the query text in the command palette from the last query? (ie. search the command palette for `open`, close it, then when you open it, `open` is still in the search input and the same results are shown)

**Comment by pawelphilipczyk** [comment]
I'm pretty sure @muhasturk meant exactly that and I was just thinking the same thing.

**Comment by mnquintana** [comment]
@izuzak I'm going to reopen this then, since I think this is a slightly different request than #18.

**Comment by colin-kiegel** [comment]
+1 :-)

**Comment by caleb531** [comment]
+1—the Fuzzy Finder already has this ability, and I'd love to see it for the Command Palette also.

**Comment by colin-kiegel** [comment]
it might be possible to copy the implementation of fuzzy finder then. I usually don't work with javascript, but I might give it a look.

**Comment by caleb531** [comment]
Great! For your convenience, I've pinpointed the location where the setting (called preserveLastSearch) is referenced:
https://github.com/atom/fuzzy-finder/blob/51f1f2415ecbfab785596825a011c1d2fa2658d3/lib/fuzzy-finder-view.coffee#L35

**Comment by colin-kiegel** [comment]
The code of the command-palette appears to be in some archive `/usr/share/atom/resources/app.asar` (https://github.com/atom/asar) - among all other core-packages, if I am not mistaken. That adds some difficulty for me right now.

-> I'll leave it for someone more familiar with that matter. But thanks for the hint.

**Comment by mnquintana** [comment]
If you're interested in hacking on the Command Palette, take a look at https://github.com/atom/atom/blob/master/docs/contributing-to-packages.md (hint: it doesn't involve hacking into your local ASAR archive :wink:)

**Comment by colin-kiegel** [comment]
Thx for the hint, but coffee script is just not my playground. Anyone else? :-)

**Comment by caleb531** [comment]
Oh, what the heck—I'll take a shot at it. :)

I'll keep this issue up to date with my progress, assuming I can get this working (though it looks fairly straightforward from looking at the source).

**Comment by caleb531** [comment]
Okay, I have good news and bad news.

**Good News:** I was able to implement the basic behavior, and I've updated the command-palette spec to verify its correct behavior.
**Bad News:** The behavior is enabled when the `preserveLastSearch` setting is *true*, however the package as-is does not have any existing config settings, and it seems to me adding a setting would require reorganizing the source a bit (there's only one file inside `lib`, as opposed to the several I see in other packages). I contend that I don't have enough experience with CoffeeScript or with the Atom API to do this.

Regardless, my changes are available on my forked repository, [caleb531/command-palette](https://github.com/caleb531/command-palette). Anyone up to the task of finishing the feature's implementation is welcome to fork my work and add the config setting (however that's done) so it's visible in the Settings UI.

Caleb

**Comment by goldo** [comment]
Have we got any news about this ? I am really interested in it :)

**Comment by harrisitservices** [comment]
Looks like this was merged into master. When will a new release be pushed so I can have the changes in Atom without having to pull down the code manually?

**Comment by 50Wliu** [comment]
I've published v0.39.0 - thanks for the heads up!  This feature should be available starting in Atom 1.12.0.
