### ISSUE TITLE
can't read property findKeyBindings on undefined

### ISSUE THREAD

**Issue by mark-hahn** [atom/command-palette#48]
I'm posting this here immediately instead of chasing it down myself because the property `keymap` is missing on Atom which seems pretty basic to core code.  I searched this repo's source for `keymap` and got nothing, which makes no sense.  I've never had much luck with github search.

```
   CommandPaletteView.prototype.attach = function(callback) {
      var commands, workSpaceView;
      this.callback = callback;
      this.storeFocusedElement();
      workSpaceView = atom.views.getView(atom.workspace);
      this.keyBindings = atom.keymap.findKeyBindings({        <<------ 
        target: workSpaceView
```

Atom 209
ubuntu 14.0.4
apm  0.171.0
npm  2.5.1
node 0.10.35
python 2.7.3
git 1.7.9.5

**Comment by kevinsawicki** [comment]
Yeah, it is `atom.keymaps` now, `atom.keymap` was removed when the 1.0 API shipped.

It should have been fixed and released awhile though via https://github.com/atom/command-palette/commit/4c083903a270c751237cb96f232cbf6d3e826b9e

**Comment by mark-hahn** [comment]
Sorry.  My bad.  I had copied that code and thought it was your code.
