### ISSUE TITLE
Command Pallete ignores custom keymap

### ISSUE THREAD

**Issue by jwkicklighter** [atom/command-palette#49]
Originally posted in https://github.com/atom/atom:

I'm a user of IntelliJ, so I like using ctrl-shift-a for "actions," rather than the default ctrl-shift-p for "palette." I've changed my keymap so that ctrl-shift-a should toggle the command palette (and this is reflected in the Packages > Command Palette menu) but it seems stuck on the old keymap. And yes, I've restarted Atom.

**Comment by lee-dohm** [comment]
Have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it.

**Comment by jwkicklighter** [comment]
I did not, that helped me love it. Thanks!
