### ISSUE TITLE
[Feature Request] A way to set the syntax for document

### ISSUE THREAD

**Issue by inooid** [atom/command-palette#50]
When opening a new file to mark something up, I used to use `alt+cmd+p` to set the syntax highlighter to a certain type.

**Example:** Sublime Text set syntax
![Set syntax sublime text](https://cloud.githubusercontent.com/assets/1291263/8393879/6b07e8ba-1d22-11e5-93ab-2e9f6f267ad2.png)

**Atom's perspective:**
![screen shot 2015-06-27 at 23 18 17](https://cloud.githubusercontent.com/assets/1291263/8393885/cccd6142-1d22-11e5-80f7-559e90987f19.png)

This would be a very helpful for me at least. Keep up the good work!

**Comment by mnquintana** [comment]
This is already possible in Atom – search the Command Palette for Grammar Selector when an editor is active.
![screenshot 2015-06-27 21 54 15](https://cloud.githubusercontent.com/assets/823545/8394795/1f520d66-1d17-11e5-9bf6-c22b41ec0815.png)
