### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by srinathv** [atom/command-palette#54]
For some reason shift+command+p stopped working.  Also ctrl+. does not activate the capture mech.

**Comment by srinathv** [comment]
srinathv@Paratools-SV-MBPro.local<pdtoolkit-3.20> $apm list
Built-in Atom packages (88)
├── archive-view@0.58.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.0
├── autocomplete-css@0.8.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.17.4
├── autocomplete-snippets@1.7.0
├── autoflow@0.25.0
├── autosave@0.22.0
├── background-tips@0.25.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.35.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.53.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.21.0
├── exception-reporting@0.35.0
├── find-and-replace@0.174.2
├── fuzzy-finder@0.87.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.33.0
├── language-c@0.45.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.6.0
├── language-css@0.32.0
├── language-gfm@0.78.0
├── language-git@0.10.0
├── language-go@0.30.0
├── language-html@0.40.0
├── language-hyperlink@0.14.0
├── language-java@0.15.0
├── language-javascript@0.80.0
├── language-json@0.15.0
├── language-less@0.28.0
├── language-make@0.14.0
├── language-mustache@0.12.0
├── language-objective-c@0.15.0
├── language-perl@0.28.0
├── language-php@0.27.0
├── language-property-list@0.8.0
├── language-python@0.37.0
├── language-ruby@0.56.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.39.0
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.25.0
├── language-toml@0.16.0
├── language-xml@0.30.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.57.0
├── one-dark-syntax@1.0.0
├── one-dark-ui@1.0.0
├── one-light-syntax@1.0.0
├── one-light-ui@1.0.0
├── open-on-github@0.37.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.211.0
├── snippets@0.95.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.59.0
├── status-bar@0.75.1
├── styleguide@0.44.0
├── symbols-view@0.100.0
├── tabs@0.82.0
├── timecop@0.31.0
├── tree-view@0.177.0
├── update-package-dependencies@0.10.0
├── welcome@0.29.0
├── whitespace@0.30.0
└── wrap-guide@0.35.0

/Users/srinathv/.atom/packages (13)
├── autocomplete-ctags@0.3.0
├── autocomplete-python@0.5.3
├── default-language@0.2.0
├── ex-mode@0.6.1
├── git-plus@5.2.2
├── language-cython@0.3.0
├── language-diff@0.3.0
├── language-fortran@1.5.6
├── language-restructuredtext@0.7.0
├── linter@1.2.4
├── merge-conflicts@1.3.4
├── remote-edit@1.8.14
└── vim-mode@0.57.0

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by srinathv** [comment]
yes...btw:

la /usr/local/bin/atom
lrwxr-xr-x  1 srinathv  admin  53 Jul 28 11:55 /usr/local/bin/atom -> /Applications/Atom.app/Contents/Resources/app/atom.sh

I did a fresh reinstall of atom today.

**Comment by mnquintana** [comment]
Try opening the Keybinding Resolver with <kbd>Cmd-.</kbd> (instead of <kbd>Ctrl-.</kbd>, then post a screenshot of what it says when you enter <kbd>Cmd-Shift-P</kbd>.

**Comment by srinathv** [comment]
Issue resolved after restarting (Mac OS X 10.10.4).

Sorry for the confusion.

<>Srinath


=================================
Srinath Vadlamani
=================================

**Comment by kevinsawicki** [comment]
Closing this out, thanks for letting us know.
