### ISSUE TITLE
history in command palette

### ISSUE THREAD

**Issue by rawdlite** [atom/command-palette#56]
i would love to be able to navigate the last commands chosen in the command palette.
Similar to shell history.

**Comment by xcv58** [comment]
Me too. It's a very useful feature!

**Comment by quaritexa** [comment]
:+1:

**Comment by saulonardin** [comment]
Me too, it saves a lot of typing

**Comment by marpala** [comment]
+1. If you're used to Sublime's palette, it's hard to use anything else. Sublime's also keeps track of how many times we use a command.

For example, if I use the "install package" command a lot, it knows that if I start typing `"in..."` I most likely want to use that command and it shows me exactly that as the first option.

**Comment by harryjubb** [comment]
+1 for this too! Migration from Sublime; I particularly miss the command palette remembering the last command I typed and bringing that up by default, particularly useful if you end up doing the same thing several times in a row.

**Comment by harrisitservices** [comment]
@harryjubb - Remembering the last command is already implemented in atom 1.12. You can check out atom beta to see its functionality. I do think @marpala's suggestion (keeping track of how many times a command is used) should be implemented as well.

**Comment by 50Wliu** [comment]
As the feature requested for in this issue has been implemented, I'm closing this.  Please open new issues for the other enhancements.

**Comment by brunetton** [comment]
Sorry for that question, but I'm using Atom 1.14.2 and I can't find how to recall last command.
Thanks

**Comment by rsese** [comment]
@brunetton - it's a command palette package setting, `Preserve Last Search`:

![](https://github-slack.s3.amazonaws.com/monosnap/Settings__sandboxhello-world_2017-04-20_13-27-12.png)

**Comment by brunetton** [comment]
Thanks ! Indeed I didn't realized that command palette was a package too.
It makes sense.


2017-04-20 20:28 GMT+02:00 Robert Sese <notifications@github.com>:

**Comment by rongi** [comment]
It should be a default setting
