### ISSUE TITLE
Add support for alternate scoring (fuzzaldrin)

### ISSUE THREAD

**Issue by peppy** [atom/command-palette#59]
It would be great to see support for the new alternate scoring as seen in atom/fuzzaldrin#22 to solve issues like this:

![](http://puu.sh/l7t77/a43942f435.png)
(Also of interest are others hitting the same issue at atom/fuzzaldrin#20)

@jeancroy [requested](https://github.com/jeancroy/fuzzaldrin-plus/issues/5#issuecomment-153234164) I open this issue, so here we go :).

**Comment by jeancroy** [comment]
One issue I see is that command-palette does not have a `main.cofee`, nor does it have any setting in atom.

**Comment by benogle** [comment]
Closed in #60

**Comment by peppy** [comment]
Thanks :star2:

![](http://puu.sh/lb8uY/2badbcd968.png)
