### ISSUE TITLE
Priority for contiguous blocks when searching

### ISSUE THREAD

**Issue by stared** [atom/command-palette#61]
I like that the search accepts "scattered" matches. However, shouldn't it there be some score for contiguous blocks of texts? 

For example, when I type `push` I expect it to find "Git Plus: **Push**" above "Git **P**l**us**: Stage **H**unk".

![screen shot 2015-11-18 at 23 55 02](https://cloud.githubusercontent.com/assets/1001610/11267784/9d4643a6-8ead-11e5-9a52-e8fe170207a7.png)

**Comment by 50Wliu** [comment]
Please enable the "Use Alternate Scoring" option in the Command Palette settings and see if that helps (you'll need to be using a 1.3.0 beta though).

**Comment by stared** [comment]
I see it is already in #59.

In any case, I have the last version of Atom (1.2.2) and the command-palette is 0.37.0, without an option to update.

Am I missing something?

**Comment by mnquintana** [comment]
@stared You'd need to download and install the Atom Beta channel release from https://atom.io/beta to get to try this out early - otherwise, you can wait until Atom 1.3.0 is officially released on the main channel.
