### ISSUE TITLE
Selectors with commas in them show keybindings in the palette multiple times

### ISSUE THREAD

**Issue by lee-dohm** [atom/command-palette#65]
See markdown-preview v0.157.2:

https://github.com/atom/markdown-preview/blob/v0.157.2/keymaps/markdown-preview.cson#L1-L2

Causes this:

<img width="601" alt="double-keys" src="https://cloud.githubusercontent.com/assets/1038121/12967007/aec0902c-d017-11e5-8b4e-477440fc8e5e.png">

Changing the selector to either `atom-workspace` or `atom-workspace atom-text-editor` resolves the issue.

**Comment by iolsen** [comment]
I can't repro this anymore in 1.7.0. Gonna close this since it was my report that Lee helpfully tracked down and filed.
