### ISSUE TITLE
Command Palette: Not able to set up command palette location on screen

### ISSUE THREAD

**Issue by rgrvontela** [atom/command-palette#66]
Hi

I am very new to Atom, please pardon me if this is not a bug.
When i click ctrl+shift+P for the first time crosshair appears on screen and asked me to select
1. origin
2. first edge (which I assumed as the top right edge).
3. Right Click to exit

but even after following the above steps, next time i use key combo of ctrl+shift+P same crosshair shows up.

Thanks
Raja
![screenshot1](https://cloud.githubusercontent.com/assets/5332265/13656547/c1e78fbe-e635-11e5-957c-efab591b6a73.jpg)

**Comment by 50Wliu** [comment]
Hi @rgrvontela, the Command Palette doesn't actually allow you to set the position - I'm not sure what's causing your image to show up.  If you start Atom in safe mode (`atom --safe`), does this still occur?  Thanks.

**Comment by rgrvontela** [comment]
@50Wliu Thanks Wliu!!! I found this was happening because of snipping tool installed on my PC.
