### ISSUE TITLE
Grammar Sensitive Commands

### ISSUE THREAD

**Issue by ZehCnaS34** [atom/command-palette#99]
Is there a way to only display certain commands only when a certain grammar is active? I think it's kind of weird seeing babel specific commands in the command palette while I'm editing python. I know PR #92 kind of helps me fix this issue, but I'm not sure how much.

**Comment by 50Wliu** [comment]
@ZehCnaS34 the package author just needs to scope their commands correctly, for example by using `atom-text-editor[data-grammar="source js"]` (or whatever scope Babel uses).
